### ISSUE TITLE
No response to SSDP discovery broadcasts

### ISSUE THREAD

**Issue by aetha** [mhei/u2pnpd#2]
Hi, I'm not sure if I've configured u2pnpd wrong, but I just can't seem to get my device to show up in Windows' Network browser. Running Wireshark on my ethernet interface and filtering SSDP packets shows absolutely no responses coming back from it.

**Comment by aetha** [comment]
My config
```
config u2pnpd
        option uuid 'e38eb963-c5e8-478b-b7eb-b12cecfb9622'
        option manufacturer 'Netgear'
        option manufacturerURL 'https://www.netgear.com/'
        option modelName 'WNR2200'
        option modelURL 'https://openwrt.org/toh/netgear/wnr2200'
        option friendlyName 'Flaaffy'
        option interface 'br-lan'
```

**Comment by mhei** [comment]
Sorry for late response, was traveling without good Internet access...
Back to your problem: could you post your routing table of the Netgear, and/or do you see the SSDP packets on the Netgear side with Wireshark/tcpdump/... ?

**Comment by mhei** [comment]
Closing due to no response.
